Algoritmo "exercicio 17"

Var
   n1,n2,n3,n4:caractere
   i1,i2,i3,i4:inteiro
   im:real


Inicio
      escreval("Digite 4 nomes")
      leia(n1,n2,n3,n4)
      escreval("Digite as 4 idades desses nomes")
      leia(i1,i2,i3,i4)
      im<-(i1+i2+i3+i4)/4
      escreval(n1," idade:",i1)
      escreval(n2," idade:",i2)
      escreval(n3," idade:",i3)
      escreval(n4," idade:",i4)
      escreval("media das idades:",im)
Fimalgoritmo